#15 購入履歴画面の作成
Moemi02/lamp_practice pull request #16
Opened 2020-03-16 21:57 UTC by Moemi02

購入履歴画面の作成を途中まで行いました。本日のレッスンでご指導いただきたいです。よろしくお願いします。

2020-03-17 01:20 UTC, thisprodigiousgeek requested changes
まずは購入履歴画面のcontrollerとviewが順調に進んでいますね！あとは、modelを仕上げればまずは履歴画面も完成しそうです。この調子で頑張っていきましょう！

2020-03-17 01:20 UTC, thisprodigiousgeek commented on www/view/orders_view.php
> +                  <input type="hidden" name="order_id" value="<?php print $order['order_id']; ?>">
出力の際には、必要な処理がありましたね！

2020-03-20 10:25 UTC, Moemi02 commented
購入履歴画面の作成を行いました。確認お願いいたします。

2020-03-21 11:02 UTC, Moemi02 commented
購入明細画面の作成完了しました。確認お願いします。

2020-03-21 11:50 UTC, thisprodigiousgeek requested changes
購入明細画面も完成に近づいてきましたね！素晴らしいです。残りわずかですので、コメントを参考に修正して仕上げていきましょう！

2020-03-21 11:50 UTC, thisprodigiousgeek commented on www/html/order_details.php
> +$order_id_regex = '/^[0-9]+$/';
正規表現の使い方、しっかりご理解いただけていらっしゃいますね！素晴らしいです。
今回の場合、正規表現を利用したチェックは、このファイルではなく関数で行うことで他のコントローラとの整合性が取れます。他のコントローラでどのようにチェックを行なっているか確認してみましょう。
また、現在は007などの0始まりの数値が許容されています。「正の整数」をチェックするためにはどのような正規表現を利用すべきか調べてみましょう。

2020-03-21 11:50 UTC, thisprodigiousgeek commented on www/model/order_detail.php
> +';
インデントが崩れているようですので直しておきましょう！

2020-03-21 11:50 UTC, thisprodigiousgeek commented on www/model/order_detail.php
> +function get_all_order_details($db, $order_id){
全てのorder_detailを取得するわけではないので、語弊のある関数名になっていますね！

2020-03-21 11:50 UTC, thisprodigiousgeek commented on www/view/orders_view.php
> +      <p>購入履歴はありません。</p>
現在の仕組みだと、他人の購入履歴を閲覧しようとした時に「購入履歴はありません」という表示になりそうです。
エラーメッセージとリダイレクトを実装しましょう！

2020-03-22 08:13 UTC, Moemi02 commented
昨日のレッスンで教えて頂いた箇所の修正をしました。確認お願いします。

2020-03-22 10:55 UTC, thisprodigiousgeek approved these changes
はい、こちらで各種異常系にも対応できてバッチリですね！
マージさせていただきます！

2020-03-22 10:55 UTC, merged