#17 並び替え機能の追加
Moemi02/lamp_practice pull request #18
Opened 2020-03-23 13:01 UTC by Moemi02

ひとまずタスクリストの項目に沿って実装を行いましたが、商品の並べ替えができません。

view/index_view.phpに追加した部分について
srcのパスの指定方法が合っているのか不明です。
display_itemのvalueが送られているのかどうかもわかりません。
setectフォームをページの右側に配置したいのですが、どこでcssを書けばいいのかわかりません。

よろしくお願いします。

2020-03-23 16:00 UTC, thisprodigiousgeek requested changes
順調に実装が進んでいらっしゃいますね１
まずはjsが読み込まれていないため、コメントを参考に修正してみましょう！
また、getで何も送られてきていない場合の並び順についても考慮できると良いですね！

2020-03-23 16:00 UTC, thisprodigiousgeek commented on www/view/index_view.php
> +  <script src="../www/html/assets/sort.js"></script>
まずは、シンプルにファイル名が異なっているようですね！
また、viewファイルはコントローラからincludeされているので、コントローラのある場所から見たパスにしましょう。

2020-03-23 16:00 UTC, thisprodigiousgeek commented on www/html/admin.php
> +$items = get_all_items($db, $display_item);
$display_itemがこのファイルには存在していなさそうですね！

2020-03-25 15:51 UTC, Moemi02 commented
レッスン後CSSの追加を行いました。確認お願いします。

2020-03-25 18:04 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！
課題開発お疲れ様でした！マージさせていただきます！

2020-03-25 18:04 UTC, merged