Issue/6
Moemi02/lamp_practice pull request #8
Opened 2020-03-01 09:54 UTC by Moemi02

issue/6の実装をしたのでマージをお願いします

2020-03-01 17:05 UTC, Moemi02 commented
名前付きプレースホルダーへの変更をしたのでマージをお願いします

2020-03-04 00:38 UTC, thisprodigiousgeek requested changes
順調に実装が進んでいらっしゃいますね！
名前付きプレースホルダの必要性・命名に関する問題および、不要なシングルクォートの利用がありましたので、コメントを参考に修正をお願いします！

2020-03-04 09:49 UTC, Moemi02 commented
名前付きプレースホルダーの必要性・命名に関する問題および、不要なシングルクォートの利用についての修正をしたのでマージお願いします

2020-03-04 09:55 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます。

2020-03-04 09:55 UTC, merged